version: 0.2

env:
  variables:
    SOLUTION: ./Kentico/WebApp.sln
    PACKAGE_DIRECTORY: Kentico/packages
    DOTNET_FRAMEWORK: 4.8
phases:
  build:
    commands:
    - nuget restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY
    - msbuild $env:SOLUTION /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:PackageLocation="C:\codebuild\artifacts"
