version: 0.2

env:
  variables:
    SOLUTION: ./Kentico/WebApp.sln
    PACKAGE_DIRECTORY: Kentico/packages
    DOTNET_FRAMEWORK: 4.8
phases:
  build:
    commands:
    - dir
    - 'md C:\srcbld'
    - 'Xcopy $env:CODEBUILD_SRC_DIR C:\srcbld /O /X /E /H /K'
    - 'cd C:\srcbld'
    - 'dir'
    - 'dir C:\srcbld\Kentico\CMS\'
    - nuget restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY
    - msbuild $env:SOLUTION /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:PackageLocation="C:\codebuild\artifacts"
  post_build:
    commands:
    - 'cd C:\srcbld\Kentico\CMS\obj\Release\Package\PackageTmp; Compress-Archive -Path C:\srcbld\Kentico\CMS\obj\Release\Package\PackageTmp\* -DestinationPath kentico-cms.zip'
    - 'dir'
    - 'copy C:\srcbld\aws-windows-deployment-manifest.json .'
    - 'xcopy C:\srcbld\.ebextensions .ebextensions /E /H /C /I'
    - 'dir'
artifacts:
  files:
    - 'kentico-cms.zip'
    - 'aws-windows-deployment-manifest.json'
    - .ebextensions/* 
  base-directory: 'C:\srcbld\Kentico\CMS\obj\Release\Package\PackageTmp'
