//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Common;

[assembly: RegisterDocumentType(BaseSiteSettings.CLASS_NAME, typeof(BaseSiteSettings))]

namespace CMS.DocumentEngine.Types.Common
{
	/// <summary>
	/// Represents a content item of type BaseSiteSettings.
	/// </summary>
	public partial class BaseSiteSettings : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Common.BaseSiteSettings";


		/// <summary>
		/// The instance of the class that provides extended API for working with BaseSiteSettings fields.
		/// </summary>
		private readonly BaseSiteSettingsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BaseSiteSettingsID.
		/// </summary>
		[DatabaseIDField]
		public int BaseSiteSettingsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BaseSiteSettingsID"), 0);
			}
			set
			{
				SetValue("BaseSiteSettingsID", value);
			}
		}


		/// <summary>
		/// Copyright Text.
		/// </summary>
		[DatabaseField]
		public string CopyrightText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CopyrightText"), @"");
			}
			set
			{
				SetValue("CopyrightText", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BaseSiteSettings fields.
		/// </summary>
		[RegisterProperty]
		public BaseSiteSettingsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BaseSiteSettings fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BaseSiteSettingsFields : AbstractHierarchicalObject<BaseSiteSettingsFields>
		{
			/// <summary>
			/// The content item of type BaseSiteSettings that is a target of the extended API.
			/// </summary>
			private readonly BaseSiteSettings mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BaseSiteSettingsFields" /> class with the specified content item of type BaseSiteSettings.
			/// </summary>
			/// <param name="instance">The content item of type BaseSiteSettings that is a target of the extended API.</param>
			public BaseSiteSettingsFields(BaseSiteSettings instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BaseSiteSettingsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BaseSiteSettingsID;
				}
				set
				{
					mInstance.BaseSiteSettingsID = value;
				}
			}


			/// <summary>
			/// Copyright Text.
			/// </summary>
			public string CopyrightText
			{
				get
				{
					return mInstance.CopyrightText;
				}
				set
				{
					mInstance.CopyrightText = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BaseSiteSettings" /> class.
		/// </summary>
		public BaseSiteSettings() : base(CLASS_NAME)
		{
			mFields = new BaseSiteSettingsFields(this);
		}

		#endregion
	}
}