//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.Common;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(CalloutCardFolder.CLASS_NAME, typeof(CalloutCardFolder))]

namespace CMS.DocumentEngine.Types.Common
{
	/// <summary>
	/// Represents a content item of type CalloutCardFolder.
	/// </summary>
	public partial class CalloutCardFolder : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Common.CalloutCardFolder";


		/// <summary>
		/// The instance of the class that provides extended API for working with CalloutCardFolder fields.
		/// </summary>
		private readonly CalloutCardFolderFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with CalloutCardFolder fields.
		/// </summary>
		[RegisterProperty]
		public CalloutCardFolderFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CalloutCardFolder fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CalloutCardFolderFields : AbstractHierarchicalObject<CalloutCardFolderFields>
		{
			/// <summary>
			/// The content item of type CalloutCardFolder that is a target of the extended API.
			/// </summary>
			private readonly CalloutCardFolder mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CalloutCardFolderFields" /> class with the specified content item of type CalloutCardFolder.
			/// </summary>
			/// <param name="instance">The content item of type CalloutCardFolder that is a target of the extended API.</param>
			public CalloutCardFolderFields(CalloutCardFolder instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CalloutCardFolder" /> class.
		/// </summary>
		public CalloutCardFolder() : base(CLASS_NAME)
		{
			mFields = new CalloutCardFolderFields(this);
		}

		#endregion
	}
}