//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.Common;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ContentDetailFolder.CLASS_NAME, typeof(ContentDetailFolder))]

namespace CMS.DocumentEngine.Types.Common
{
	/// <summary>
	/// Represents a content item of type ContentDetailFolder.
	/// </summary>
	public partial class ContentDetailFolder : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Common.ContentDetailFolder";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContentDetailFolder fields.
		/// </summary>
		private readonly ContentDetailFolderFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with ContentDetailFolder fields.
		/// </summary>
		[RegisterProperty]
		public ContentDetailFolderFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ContentDetailFolder fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContentDetailFolderFields : AbstractHierarchicalObject<ContentDetailFolderFields>
		{
			/// <summary>
			/// The content item of type ContentDetailFolder that is a target of the extended API.
			/// </summary>
			private readonly ContentDetailFolder mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContentDetailFolderFields" /> class with the specified content item of type ContentDetailFolder.
			/// </summary>
			/// <param name="instance">The content item of type ContentDetailFolder that is a target of the extended API.</param>
			public ContentDetailFolderFields(ContentDetailFolder instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContentDetailFolder" /> class.
		/// </summary>
		public ContentDetailFolder() : base(CLASS_NAME)
		{
			mFields = new ContentDetailFolderFields(this);
		}

		#endregion
	}
}