//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Common;

[assembly: RegisterDocumentType(ExampleContent.CLASS_NAME, typeof(ExampleContent))]

namespace CMS.DocumentEngine.Types.Common
{
	/// <summary>
	/// Represents a content item of type ExampleContent.
	/// </summary>
	public partial class ExampleContent : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Common.ExampleContent";


		/// <summary>
		/// The instance of the class that provides extended API for working with ExampleContent fields.
		/// </summary>
		private readonly ExampleContentFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ExampleContentID.
		/// </summary>
		[DatabaseIDField]
		public int ExampleContentID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ExampleContentID"), 0);
			}
			set
			{
				SetValue("ExampleContentID", value);
			}
		}


		/// <summary>
		/// Placeholder.
		/// </summary>
		[DatabaseField]
		public string Placeholder
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Placeholder"), @"");
			}
			set
			{
				SetValue("Placeholder", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ExampleContent fields.
		/// </summary>
		[RegisterProperty]
		public ExampleContentFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ExampleContent fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ExampleContentFields : AbstractHierarchicalObject<ExampleContentFields>
		{
			/// <summary>
			/// The content item of type ExampleContent that is a target of the extended API.
			/// </summary>
			private readonly ExampleContent mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ExampleContentFields" /> class with the specified content item of type ExampleContent.
			/// </summary>
			/// <param name="instance">The content item of type ExampleContent that is a target of the extended API.</param>
			public ExampleContentFields(ExampleContent instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ExampleContentID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ExampleContentID;
				}
				set
				{
					mInstance.ExampleContentID = value;
				}
			}


			/// <summary>
			/// Placeholder.
			/// </summary>
			public string Placeholder
			{
				get
				{
					return mInstance.Placeholder;
				}
				set
				{
					mInstance.Placeholder = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ExampleContent" /> class.
		/// </summary>
		public ExampleContent() : base(CLASS_NAME)
		{
			mFields = new ExampleContentFields(this);
		}

		#endregion
	}
}