//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.Common;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(GlobalContentFolder.CLASS_NAME, typeof(GlobalContentFolder))]

namespace CMS.DocumentEngine.Types.Common
{
	/// <summary>
	/// Represents a content item of type GlobalContentFolder.
	/// </summary>
	public partial class GlobalContentFolder : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Common.GlobalContentFolder";


		/// <summary>
		/// The instance of the class that provides extended API for working with GlobalContentFolder fields.
		/// </summary>
		private readonly GlobalContentFolderFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with GlobalContentFolder fields.
		/// </summary>
		[RegisterProperty]
		public GlobalContentFolderFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with GlobalContentFolder fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class GlobalContentFolderFields : AbstractHierarchicalObject<GlobalContentFolderFields>
		{
			/// <summary>
			/// The content item of type GlobalContentFolder that is a target of the extended API.
			/// </summary>
			private readonly GlobalContentFolder mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="GlobalContentFolderFields" /> class with the specified content item of type GlobalContentFolder.
			/// </summary>
			/// <param name="instance">The content item of type GlobalContentFolder that is a target of the extended API.</param>
			public GlobalContentFolderFields(GlobalContentFolder instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="GlobalContentFolder" /> class.
		/// </summary>
		public GlobalContentFolder() : base(CLASS_NAME)
		{
			mFields = new GlobalContentFolderFields(this);
		}

		#endregion
	}
}