//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Common;

[assembly: RegisterDocumentType(GlobalContent.CLASS_NAME, typeof(GlobalContent))]

namespace CMS.DocumentEngine.Types.Common
{
	/// <summary>
	/// Represents a content item of type GlobalContent.
	/// </summary>
	public partial class GlobalContent : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Common.GlobalContent";


		/// <summary>
		/// The instance of the class that provides extended API for working with GlobalContent fields.
		/// </summary>
		private readonly GlobalContentFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// GlobalContentID.
		/// </summary>
		[DatabaseIDField]
		public int GlobalContentID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("GlobalContentID"), 0);
			}
			set
			{
				SetValue("GlobalContentID", value);
			}
		}


		/// <summary>
		/// Placeholder.
		/// </summary>
		[DatabaseField]
		public string Placeholder
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Placeholder"), @"");
			}
			set
			{
				SetValue("Placeholder", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with GlobalContent fields.
		/// </summary>
		[RegisterProperty]
		public GlobalContentFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with GlobalContent fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class GlobalContentFields : AbstractHierarchicalObject<GlobalContentFields>
		{
			/// <summary>
			/// The content item of type GlobalContent that is a target of the extended API.
			/// </summary>
			private readonly GlobalContent mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="GlobalContentFields" /> class with the specified content item of type GlobalContent.
			/// </summary>
			/// <param name="instance">The content item of type GlobalContent that is a target of the extended API.</param>
			public GlobalContentFields(GlobalContent instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// GlobalContentID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.GlobalContentID;
				}
				set
				{
					mInstance.GlobalContentID = value;
				}
			}


			/// <summary>
			/// Placeholder.
			/// </summary>
			public string Placeholder
			{
				get
				{
					return mInstance.Placeholder;
				}
				set
				{
					mInstance.Placeholder = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="GlobalContent" /> class.
		/// </summary>
		public GlobalContent() : base(CLASS_NAME)
		{
			mFields = new GlobalContentFields(this);
		}

		#endregion
	}
}