//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Common;

[assembly: RegisterDocumentType(Location.CLASS_NAME, typeof(Location))]

namespace CMS.DocumentEngine.Types.Common
{
	/// <summary>
	/// Represents a content item of type Location.
	/// </summary>
	public partial class Location : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Common.Location";


		/// <summary>
		/// The instance of the class that provides extended API for working with Location fields.
		/// </summary>
		private readonly LocationFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// RiseLocationID.
		/// </summary>
		[DatabaseIDField]
		public int LocationID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("LocationID"), 0);
			}
			set
			{
				SetValue("LocationID", value);
			}
		}


		/// <summary>
		/// Address.
		/// </summary>
		[DatabaseField]
		public string Address1
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Address1"), @"");
			}
			set
			{
				SetValue("Address1", value);
			}
		}


		/// <summary>
		/// Address 2.
		/// </summary>
		[DatabaseField]
		public string Address2
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Address2"), @"");
			}
			set
			{
				SetValue("Address2", value);
			}
		}


		/// <summary>
		/// City.
		/// </summary>
		[DatabaseField]
		public string City
		{
			get
			{
				return ValidationHelper.GetString(GetValue("City"), @"");
			}
			set
			{
				SetValue("City", value);
			}
		}


		/// <summary>
		/// State.
		/// </summary>
		[DatabaseField]
		public string State
		{
			get
			{
				return ValidationHelper.GetString(GetValue("State"), @"");
			}
			set
			{
				SetValue("State", value);
			}
		}


		/// <summary>
		/// Zipcode.
		/// </summary>
		[DatabaseField]
		public string Zipcode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Zipcode"), @"");
			}
			set
			{
				SetValue("Zipcode", value);
			}
		}


		/// <summary>
		/// Latitude.
		/// </summary>
		[DatabaseField]
		public double Latitude
		{
			get
			{
				return ValidationHelper.GetDouble(GetValue("Latitude"), 0);
			}
			set
			{
				SetValue("Latitude", value);
			}
		}


		/// <summary>
		/// Longitude.
		/// </summary>
		[DatabaseField]
		public double Longitude
		{
			get
			{
				return ValidationHelper.GetDouble(GetValue("Longitude"), 0);
			}
			set
			{
				SetValue("Longitude", value);
			}
		}


		/// <summary>
		/// Phone Number.
		/// </summary>
		[DatabaseField]
		public string PhoneNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PhoneNumber"), @"");
			}
			set
			{
				SetValue("PhoneNumber", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Location fields.
		/// </summary>
		[RegisterProperty]
		public LocationFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Location fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class LocationFields : AbstractHierarchicalObject<LocationFields>
		{
			/// <summary>
			/// The content item of type Location that is a target of the extended API.
			/// </summary>
			private readonly Location mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="LocationFields" /> class with the specified content item of type Location.
			/// </summary>
			/// <param name="instance">The content item of type Location that is a target of the extended API.</param>
			public LocationFields(Location instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// RiseLocationID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.LocationID;
				}
				set
				{
					mInstance.LocationID = value;
				}
			}


			/// <summary>
			/// Address.
			/// </summary>
			public string Address1
			{
				get
				{
					return mInstance.Address1;
				}
				set
				{
					mInstance.Address1 = value;
				}
			}


			/// <summary>
			/// Address 2.
			/// </summary>
			public string Address2
			{
				get
				{
					return mInstance.Address2;
				}
				set
				{
					mInstance.Address2 = value;
				}
			}


			/// <summary>
			/// City.
			/// </summary>
			public string City
			{
				get
				{
					return mInstance.City;
				}
				set
				{
					mInstance.City = value;
				}
			}


			/// <summary>
			/// State.
			/// </summary>
			public string State
			{
				get
				{
					return mInstance.State;
				}
				set
				{
					mInstance.State = value;
				}
			}


			/// <summary>
			/// Zipcode.
			/// </summary>
			public string Zipcode
			{
				get
				{
					return mInstance.Zipcode;
				}
				set
				{
					mInstance.Zipcode = value;
				}
			}


			/// <summary>
			/// Latitude.
			/// </summary>
			public double Latitude
			{
				get
				{
					return mInstance.Latitude;
				}
				set
				{
					mInstance.Latitude = value;
				}
			}


			/// <summary>
			/// Longitude.
			/// </summary>
			public double Longitude
			{
				get
				{
					return mInstance.Longitude;
				}
				set
				{
					mInstance.Longitude = value;
				}
			}


			/// <summary>
			/// Phone Number.
			/// </summary>
			public string PhoneNumber
			{
				get
				{
					return mInstance.PhoneNumber;
				}
				set
				{
					mInstance.PhoneNumber = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Location" /> class.
		/// </summary>
		public Location() : base(CLASS_NAME)
		{
			mFields = new LocationFields(this);
		}

		#endregion
	}
}