//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Common;

[assembly: RegisterDocumentType(MenuCard.CLASS_NAME, typeof(MenuCard))]

namespace CMS.DocumentEngine.Types.Common
{
	/// <summary>
	/// Represents a content item of type MenuCard.
	/// </summary>
	public partial class MenuCard : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Common.MenuCard";


		/// <summary>
		/// The instance of the class that provides extended API for working with MenuCard fields.
		/// </summary>
		private readonly MenuCardFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// MenuCardID.
		/// </summary>
		[DatabaseIDField]
		public int MenuCardID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("MenuCardID"), 0);
			}
			set
			{
				SetValue("MenuCardID", value);
			}
		}


		/// <summary>
		/// Page.
		/// </summary>
		[DatabaseField]
		public Guid Page
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("Page"), Guid.Empty);
			}
			set
			{
				SetValue("Page", value);
			}
		}


		/// <summary>
		/// Label.
		/// </summary>
		[DatabaseField]
		public string Label
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Label"), @"");
			}
			set
			{
				SetValue("Label", value);
			}
		}


		/// <summary>
		/// Text.
		/// </summary>
		[DatabaseField]
		public string Text
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Text"), @"");
			}
			set
			{
				SetValue("Text", value);
			}
		}


		/// <summary>
		/// Image.
		/// </summary>
		[DatabaseField]
		public string Image
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Image"), @"");
			}
			set
			{
				SetValue("Image", value);
			}
		}


		/// <summary>
		/// Image Position.
		/// </summary>
		[DatabaseField]
		public string ImagePosition
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ImagePosition"), @"");
			}
			set
			{
				SetValue("ImagePosition", value);
			}
		}


		/// <summary>
		/// Link URL.
		/// </summary>
		[DatabaseField]
		public string LinkUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkUrl"), @"");
			}
			set
			{
				SetValue("LinkUrl", value);
			}
		}


		/// <summary>
		/// External Link?.
		/// </summary>
		[DatabaseField]
		public bool IsExternal
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IsExternal"), false);
			}
			set
			{
				SetValue("IsExternal", value);
			}
		}


		/// <summary>
		/// Categories.
		/// </summary>
		[DatabaseField]
		public string Categories1
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Categories"), @"");
			}
			set
			{
				SetValue("Categories", value);
			}
		}


		/// <summary>
		/// Preview Title (Override).
		/// </summary>
		[DatabaseField]
		public string PreviewTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PreviewTitle"), @"");
			}
			set
			{
				SetValue("PreviewTitle", value);
			}
		}


		/// <summary>
		/// Preview Text (Override).
		/// </summary>
		[DatabaseField]
		public string PreviewText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PreviewText"), @"");
			}
			set
			{
				SetValue("PreviewText", value);
			}
		}


		/// <summary>
		/// Hide Preview Text (Override).
		/// </summary>
		[DatabaseField]
		public bool HidePreviewText
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("HidePreviewText"), false);
			}
			set
			{
				SetValue("HidePreviewText", value);
			}
		}


		/// <summary>
		/// Preview Image (Override).
		/// </summary>
		[DatabaseField]
		public string PreviewImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PreviewImage"), @"");
			}
			set
			{
				SetValue("PreviewImage", value);
			}
		}


		/// <summary>
		/// Preview Cta Label (Override).
		/// </summary>
		[DatabaseField]
		public string PreviewCtaLabel
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PreviewCtaLabel"), @"");
			}
			set
			{
				SetValue("PreviewCtaLabel", value);
			}
		}


		/// <summary>
		/// CmsFormScripts.
		/// </summary>
		[DatabaseField]
		public string CmsFormScripts
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CmsFormScripts"), @"");
			}
			set
			{
				SetValue("CmsFormScripts", value);
			}
		}


		/// <summary>
		/// Content Migration Label.
		/// </summary>
		[DatabaseField]
		public string ContentMigrationLabel
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContentMigrationLabel"), @"");
			}
			set
			{
				SetValue("ContentMigrationLabel", value);
			}
		}


		/// <summary>
		/// Content Migration Comment.
		/// </summary>
		[DatabaseField]
		public string ContentMigrationComment
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContentMigrationComment"), @"");
			}
			set
			{
				SetValue("ContentMigrationComment", value);
			}
		}


		/// <summary>
		/// Content Migration External Id.
		/// </summary>
		[DatabaseField]
		public string ContentMigrationExternalId
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContentMigrationExternalId"), @"");
			}
			set
			{
				SetValue("ContentMigrationExternalId", value);
			}
		}


		/// <summary>
		/// Content Migration Type.
		/// </summary>
		[DatabaseField]
		public string ContentMigrationType
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContentMigrationType"), @"");
			}
			set
			{
				SetValue("ContentMigrationType", value);
			}
		}


		/// <summary>
		/// Content Migration Relationship Id.
		/// </summary>
		[DatabaseField]
		public string ContentMigrationRelationshipId
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContentMigrationRelationshipId"), @"");
			}
			set
			{
				SetValue("ContentMigrationRelationshipId", value);
			}
		}


		/// <summary>
		/// Content Migration Old Url.
		/// </summary>
		[DatabaseField]
		public string ContentMigrationOldUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContentMigrationOldUrl"), @"");
			}
			set
			{
				SetValue("ContentMigrationOldUrl", value);
			}
		}


		/// <summary>
		/// Content Migration New Url.
		/// </summary>
		[DatabaseField]
		public string ContentMigrationNewUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContentMigrationNewUrl"), @"");
			}
			set
			{
				SetValue("ContentMigrationNewUrl", value);
			}
		}


		/// <summary>
		/// Content Migration New Node Alias Path.
		/// </summary>
		[DatabaseField]
		public string ContentMigrationNewNodeAliasPath
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContentMigrationNewNodeAliasPath"), @"");
			}
			set
			{
				SetValue("ContentMigrationNewNodeAliasPath", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with MenuCard fields.
		/// </summary>
		[RegisterProperty]
		public MenuCardFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with MenuCard fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class MenuCardFields : AbstractHierarchicalObject<MenuCardFields>
		{
			/// <summary>
			/// The content item of type MenuCard that is a target of the extended API.
			/// </summary>
			private readonly MenuCard mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="MenuCardFields" /> class with the specified content item of type MenuCard.
			/// </summary>
			/// <param name="instance">The content item of type MenuCard that is a target of the extended API.</param>
			public MenuCardFields(MenuCard instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// MenuCardID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.MenuCardID;
				}
				set
				{
					mInstance.MenuCardID = value;
				}
			}


			/// <summary>
			/// Page.
			/// </summary>
			public Guid Page
			{
				get
				{
					return mInstance.Page;
				}
				set
				{
					mInstance.Page = value;
				}
			}


			/// <summary>
			/// Label.
			/// </summary>
			public string Label
			{
				get
				{
					return mInstance.Label;
				}
				set
				{
					mInstance.Label = value;
				}
			}


			/// <summary>
			/// Text.
			/// </summary>
			public string Text
			{
				get
				{
					return mInstance.Text;
				}
				set
				{
					mInstance.Text = value;
				}
			}


			/// <summary>
			/// Image.
			/// </summary>
			public string Image
			{
				get
				{
					return mInstance.Image;
				}
				set
				{
					mInstance.Image = value;
				}
			}


			/// <summary>
			/// Image Position.
			/// </summary>
			public string ImagePosition
			{
				get
				{
					return mInstance.ImagePosition;
				}
				set
				{
					mInstance.ImagePosition = value;
				}
			}


			/// <summary>
			/// Link URL.
			/// </summary>
			public string LinkUrl
			{
				get
				{
					return mInstance.LinkUrl;
				}
				set
				{
					mInstance.LinkUrl = value;
				}
			}


			/// <summary>
			/// External Link?.
			/// </summary>
			public bool IsExternal
			{
				get
				{
					return mInstance.IsExternal;
				}
				set
				{
					mInstance.IsExternal = value;
				}
			}


			/// <summary>
			/// Categories.
			/// </summary>
			public string Categories
			{
				get
				{
					return mInstance.Categories1;
				}
				set
				{
					mInstance.Categories1 = value;
				}
			}


			/// <summary>
			/// Preview Title (Override).
			/// </summary>
			public string PreviewTitle
			{
				get
				{
					return mInstance.PreviewTitle;
				}
				set
				{
					mInstance.PreviewTitle = value;
				}
			}


			/// <summary>
			/// Preview Text (Override).
			/// </summary>
			public string PreviewText
			{
				get
				{
					return mInstance.PreviewText;
				}
				set
				{
					mInstance.PreviewText = value;
				}
			}


			/// <summary>
			/// Hide Preview Text (Override).
			/// </summary>
			public bool HidePreviewText
			{
				get
				{
					return mInstance.HidePreviewText;
				}
				set
				{
					mInstance.HidePreviewText = value;
				}
			}


			/// <summary>
			/// Preview Image (Override).
			/// </summary>
			public string PreviewImage
			{
				get
				{
					return mInstance.PreviewImage;
				}
				set
				{
					mInstance.PreviewImage = value;
				}
			}


			/// <summary>
			/// Preview Cta Label (Override).
			/// </summary>
			public string PreviewCtaLabel
			{
				get
				{
					return mInstance.PreviewCtaLabel;
				}
				set
				{
					mInstance.PreviewCtaLabel = value;
				}
			}


			/// <summary>
			/// CmsFormScripts.
			/// </summary>
			public string CmsFormScripts
			{
				get
				{
					return mInstance.CmsFormScripts;
				}
				set
				{
					mInstance.CmsFormScripts = value;
				}
			}


			/// <summary>
			/// Content Migration Label.
			/// </summary>
			public string ContentMigrationLabel
			{
				get
				{
					return mInstance.ContentMigrationLabel;
				}
				set
				{
					mInstance.ContentMigrationLabel = value;
				}
			}


			/// <summary>
			/// Content Migration Comment.
			/// </summary>
			public string ContentMigrationComment
			{
				get
				{
					return mInstance.ContentMigrationComment;
				}
				set
				{
					mInstance.ContentMigrationComment = value;
				}
			}


			/// <summary>
			/// Content Migration External Id.
			/// </summary>
			public string ContentMigrationExternalId
			{
				get
				{
					return mInstance.ContentMigrationExternalId;
				}
				set
				{
					mInstance.ContentMigrationExternalId = value;
				}
			}


			/// <summary>
			/// Content Migration Type.
			/// </summary>
			public string ContentMigrationType
			{
				get
				{
					return mInstance.ContentMigrationType;
				}
				set
				{
					mInstance.ContentMigrationType = value;
				}
			}


			/// <summary>
			/// Content Migration Relationship Id.
			/// </summary>
			public string ContentMigrationRelationshipId
			{
				get
				{
					return mInstance.ContentMigrationRelationshipId;
				}
				set
				{
					mInstance.ContentMigrationRelationshipId = value;
				}
			}


			/// <summary>
			/// Content Migration Old Url.
			/// </summary>
			public string ContentMigrationOldUrl
			{
				get
				{
					return mInstance.ContentMigrationOldUrl;
				}
				set
				{
					mInstance.ContentMigrationOldUrl = value;
				}
			}


			/// <summary>
			/// Content Migration New Url.
			/// </summary>
			public string ContentMigrationNewUrl
			{
				get
				{
					return mInstance.ContentMigrationNewUrl;
				}
				set
				{
					mInstance.ContentMigrationNewUrl = value;
				}
			}


			/// <summary>
			/// Content Migration New Node Alias Path.
			/// </summary>
			public string ContentMigrationNewNodeAliasPath
			{
				get
				{
					return mInstance.ContentMigrationNewNodeAliasPath;
				}
				set
				{
					mInstance.ContentMigrationNewNodeAliasPath = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="MenuCard" /> class.
		/// </summary>
		public MenuCard() : base(CLASS_NAME)
		{
			mFields = new MenuCardFields(this);
		}

		#endregion
	}
}