//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Common;

[assembly: RegisterDocumentType(MigratedContent.CLASS_NAME, typeof(MigratedContent))]

namespace CMS.DocumentEngine.Types.Common
{
	/// <summary>
	/// Represents a content item of type MigratedContent.
	/// </summary>
	public partial class MigratedContent : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Common.MigratedContent";


		/// <summary>
		/// The instance of the class that provides extended API for working with MigratedContent fields.
		/// </summary>
		private readonly MigratedContentFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// MigratedContentID.
		/// </summary>
		[DatabaseIDField]
		public int MigratedContentID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("MigratedContentID"), 0);
			}
			set
			{
				SetValue("MigratedContentID", value);
			}
		}


		/// <summary>
		/// Placeholder.
		/// </summary>
		[DatabaseField]
		public string Placeholder
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Placeholder"), @"");
			}
			set
			{
				SetValue("Placeholder", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with MigratedContent fields.
		/// </summary>
		[RegisterProperty]
		public MigratedContentFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with MigratedContent fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class MigratedContentFields : AbstractHierarchicalObject<MigratedContentFields>
		{
			/// <summary>
			/// The content item of type MigratedContent that is a target of the extended API.
			/// </summary>
			private readonly MigratedContent mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="MigratedContentFields" /> class with the specified content item of type MigratedContent.
			/// </summary>
			/// <param name="instance">The content item of type MigratedContent that is a target of the extended API.</param>
			public MigratedContentFields(MigratedContent instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// MigratedContentID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.MigratedContentID;
				}
				set
				{
					mInstance.MigratedContentID = value;
				}
			}


			/// <summary>
			/// Placeholder.
			/// </summary>
			public string Placeholder
			{
				get
				{
					return mInstance.Placeholder;
				}
				set
				{
					mInstance.Placeholder = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="MigratedContent" /> class.
		/// </summary>
		public MigratedContent() : base(CLASS_NAME)
		{
			mFields = new MigratedContentFields(this);
		}

		#endregion
	}
}