//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.Common;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(MigratedContentFolder.CLASS_NAME, typeof(MigratedContentFolder))]

namespace CMS.DocumentEngine.Types.Common
{
	/// <summary>
	/// Represents a content item of type MigratedContentFolder.
	/// </summary>
	public partial class MigratedContentFolder : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Common.MigratedContentFolder";


		/// <summary>
		/// The instance of the class that provides extended API for working with MigratedContentFolder fields.
		/// </summary>
		private readonly MigratedContentFolderFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with MigratedContentFolder fields.
		/// </summary>
		[RegisterProperty]
		public MigratedContentFolderFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with MigratedContentFolder fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class MigratedContentFolderFields : AbstractHierarchicalObject<MigratedContentFolderFields>
		{
			/// <summary>
			/// The content item of type MigratedContentFolder that is a target of the extended API.
			/// </summary>
			private readonly MigratedContentFolder mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="MigratedContentFolderFields" /> class with the specified content item of type MigratedContentFolder.
			/// </summary>
			/// <param name="instance">The content item of type MigratedContentFolder that is a target of the extended API.</param>
			public MigratedContentFolderFields(MigratedContentFolder instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="MigratedContentFolder" /> class.
		/// </summary>
		public MigratedContentFolder() : base(CLASS_NAME)
		{
			mFields = new MigratedContentFolderFields(this);
		}

		#endregion
	}
}