//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.Common;
using CMS.CustomTables;

[assembly: RegisterCustomTable(MenuTypeItem.CLASS_NAME, typeof(MenuTypeItem))]

namespace CMS.CustomTables.Types.Common
{
	/// <summary>
	/// Represents a content item of type MenuTypeItem.
	/// </summary>
	public partial class MenuTypeItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Common.MenuType";


		/// <summary>
		/// The instance of the class that provides extended API for working with MenuTypeItem fields.
		/// </summary>
		private readonly MenuTypeItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Code Name.
		/// </summary>
		[DatabaseField]
		public string CodeName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CodeName"), @"");
			}
			set
			{
				SetValue("CodeName", value);
			}
		}


		/// <summary>
		/// Display Name.
		/// </summary>
		[DatabaseField]
		public string DisplayName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DisplayName"), @"");
			}
			set
			{
				SetValue("DisplayName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with MenuTypeItem fields.
		/// </summary>
		[RegisterProperty]
		public MenuTypeItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with MenuTypeItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class MenuTypeItemFields : AbstractHierarchicalObject<MenuTypeItemFields>
		{
			/// <summary>
			/// The content item of type MenuTypeItem that is a target of the extended API.
			/// </summary>
			private readonly MenuTypeItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="MenuTypeItemFields" /> class with the specified content item of type MenuTypeItem.
			/// </summary>
			/// <param name="instance">The content item of type MenuTypeItem that is a target of the extended API.</param>
			public MenuTypeItemFields(MenuTypeItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Code Name.
			/// </summary>
			public string CodeName
			{
				get
				{
					return mInstance.CodeName;
				}
				set
				{
					mInstance.CodeName = value;
				}
			}


			/// <summary>
			/// Display Name.
			/// </summary>
			public string DisplayName
			{
				get
				{
					return mInstance.DisplayName;
				}
				set
				{
					mInstance.DisplayName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="MenuTypeItem" /> class.
		/// </summary>
		public MenuTypeItem() : base(CLASS_NAME)
		{
			mFields = new MenuTypeItemFields(this);
		}

		#endregion
	}
}