//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using CMS.CustomTables.Types.Common;

[assembly: RegisterCustomTable(WidgetVariantItem.CLASS_NAME, typeof(WidgetVariantItem))]

namespace CMS.CustomTables.Types.Common
{
	/// <summary>
	/// Represents a content item of type WidgetVariantItem.
	/// </summary>
	public partial class WidgetVariantItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Common.WidgetVariant";


		/// <summary>
		/// The instance of the class that provides extended API for working with WidgetVariantItem fields.
		/// </summary>
		private readonly WidgetVariantItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Variant Name.
		/// </summary>
		[DatabaseField]
		public string VariantName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("VariantName"), @"");
			}
			set
			{
				SetValue("VariantName", value);
			}
		}


		/// <summary>
		/// Class Name.
		/// </summary>
		[DatabaseField]
		public string ClassName1
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ClassName"), @"");
			}
			set
			{
				SetValue("ClassName", value);
			}
		}


		/// <summary>
		/// Widget Name.
		/// </summary>
		[DatabaseField]
		public string WidgetName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("WidgetName"), @"");
			}
			set
			{
				SetValue("WidgetName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with WidgetVariantItem fields.
		/// </summary>
		[RegisterProperty]
		public WidgetVariantItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with WidgetVariantItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class WidgetVariantItemFields : AbstractHierarchicalObject<WidgetVariantItemFields>
		{
			/// <summary>
			/// The content item of type WidgetVariantItem that is a target of the extended API.
			/// </summary>
			private readonly WidgetVariantItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="WidgetVariantItemFields" /> class with the specified content item of type WidgetVariantItem.
			/// </summary>
			/// <param name="instance">The content item of type WidgetVariantItem that is a target of the extended API.</param>
			public WidgetVariantItemFields(WidgetVariantItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Variant Name.
			/// </summary>
			public string VariantName
			{
				get
				{
					return mInstance.VariantName;
				}
				set
				{
					mInstance.VariantName = value;
				}
			}


			/// <summary>
			/// Class Name.
			/// </summary>
			public string ClassName
			{
				get
				{
					return mInstance.ClassName1;
				}
				set
				{
					mInstance.ClassName1 = value;
				}
			}


			/// <summary>
			/// Widget Name.
			/// </summary>
			public string WidgetName
			{
				get
				{
					return mInstance.WidgetName;
				}
				set
				{
					mInstance.WidgetName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="WidgetVariantItem" /> class.
		/// </summary>
		public WidgetVariantItem() : base(CLASS_NAME)
		{
			mFields = new WidgetVariantItemFields(this);
		}

		#endregion
	}
}